[package]
name = "tired-ssh"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
russh = "0.56"
ssh-key = "0.6"
anyhow = "1"
log = "0.4"
env_logger = "0.11"
shell-escape = "0.1"
clap = { version = "3.2.3", features = ["derive"] }